app/views.py
from flask import render_template, redirect, flash, request, jsonify, send_from_directory, abort, current_app, Blueprint
from .forms import UrlTextApproveForm, LayoutForm
from app.models import *
from flask_csp.csp import csp_header
from lib.utils.utils import delete_url_screens, move_url_screens
from lib.utils.html_process import extract_text_title_meta
from math import floor
from redis import Redis
import rq
import json
import os

common = Blueprint(
    'common', __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/static',
)


@common.route('/favicon.ico', methods=['GET'])
def favicon():
    return send_from_directory(os.path.join(current_app.root_path, 'static'),
                               'favicon.ico', mimetype='image/vnd.microsoft.icon')


@csp_header({"default-src": "'self'", "script-src": "'self'", "worker-src": "'self'"})
@common.route('/')
@common.route('/index')
def index():
    categories = select((u.cat, count(u.id)) for u in Url if u.deleted is False and u.cat)[:]
    with_markup = select((u.cat.id, count(u.id)) for u in Url if u.has_markup is True and u.deleted is False)[:]
    with_markup = {i[0]: i[1] for i in with_markup}
    return render_template("index.html", categories=categories, with_markup=with_markup)


@common.route('/old_cat')
def old_index():
    categories = select((u.old_cat, count(u.id)) for u in Url if u.deleted is False)[:]
    return render_template("old_index.html", categories=categories)


@common.route('/oldcat/<int:idx>', methods=['GET'], defaults={'page': 1})
@common.route('/oldcat/<int:idx>/page/<int:page>', methods=['GET'])
def old_cat(idx: int, page: int = 1):
    category = OldCategory[idx]
    if not category:
        abort(404)
    limit = int(request.args.get('limit', type=int, default=30))
    page = page if page > 0 else 1
    limit = limit if 0 < limit < 1000 else 30
    sort = request.args.get('sort', type=str, default='id')
    dir = request.args.get('dir', type=str, default='asc')
    search = request.args.get('search', type=str, default='')
    if not search.isalnum():
        search = ''
    if sort not in ['lang', 'is_main', 'url', 'host']:
        sort = 'id'
    order_by = getattr(Url, sort)
    if dir == 'desc':
        order_by = desc(order_by)
    query = category.urls.select(lambda u: u.deleted is False)
    if len(search) > 2:
        query = query.filter(lambda u: search in u.text.raw_text)
    urls = query.order_by(order_by).page(page, limit if limit > 0 else 30)
    total = query.count()
    max_page = floor(total / limit) + 1
    return render_template('cat.html',
                           cat=category,
                           route='common.old_cat',
                           urls=urls,
                           sort=sort,
                           dir=dir,
                           max_page=max_page,
                           page=page,
                           search=search
                           )


@common.route('/cat/common/<int:idx>', methods=['GET'], defaults={'page': 1})
@common.route('/cat/common/<int:idx>/page/<int:page>', methods=['GET'])
def cat(idx: int, page: int = 1):
    category = Category[idx]
    if not category:
        abort(404)
    limit = int(request.args.get('limit', type=int, default=30))
    page = page if page > 0 else 1
    limit = limit if 0 < limit < 1000 else 30
    sort = request.args.get('sort', type=str, default='id')
    dir = request.args.get('dir', type=str, default='asc')
    search = request.args.get('search', type=str, default='')
    if not search.isalnum():
        search = ''
    if sort not in ['lang', 'is_main', 'url', 'host']:
        sort = 'id'
    order_by = getattr(Url, sort)
    if dir == 'desc':
        order_by = desc(order_by)
    query = category.urls.select(lambda u: u.deleted is False)
    if len(search) > 2:
        query = query.filter(lambda u: search in u.text.raw_text)
    urls = query.order_by(order_by).page(page, limit if limit > 0 else 30)
    total = query.count()
    max_page = floor(total / limit) + 1

    return render_template('cat.html',
                           cat=category,
                           route='common.cat',
                           urls=urls,
                           sort=sort,
                           dir=dir,
                           max_page=max_page,
                           page=page,
                           search=search
                           )


@common.route('/images', methods=['GET'], defaults={'page': 1})
@common.route('/images/page/<int:page>', methods=['GET'])
def image_index(page: int = 1):
    limit = int(request.args.get('limit', type=int, default=100))
    page = page if page > 0 else 1
    limit = limit if 0 < limit < 1000 else 100
    sort = request.args.get('sort', type=str, default='layout')
    dir = request.args.get('dir', type=str, default='desc')
    search = request.args.get('search', type=str, default='')
    if not search.isalnum():
        search = ''
    if sort not in ['lang', 'is_main', 'url', 'host', 'cat', 'old_cat', 'id', 'layout']:
        sort = 'layout'
    order_by = getattr(Url, sort)
    if dir != 'asc':
        order_by = desc(order_by)
    query = Url.select(lambda u: u.deleted is False)
    if len(search) > 2:
        query = query.filter(lambda u: search in u.text.title or search in u.text.raw_text)
    urls = query.order_by(order_by).page(page, limit)
    total = query.count()
    max_page = floor(total / limit) + 1
    forms = {}
    for url in urls:
        forms[url.id] = LayoutForm(obj=url)
    return render_template('images.html',
                           route='common.image_index',
                           urls=urls,
                           sort=sort,
                           dir=dir,
                           max_page=max_page,
                           page=page,
                           forms=forms,
                           search=search
                           )


@common.route('/url/<int:url_id>', methods=['GET', 'POST'])
def show(url_id: int):
    url = Url[url_id]
    if not url:
        abort(404)
    current_cat = url.cat
    categories = select((c.id, c.name) for c in OldCategory)[:]
    form = UrlTextApproveForm(obj=url)
    form.cat.choices = categories
    if request.method == 'GET':
        form.cat.data = url.cat.id
    if form.validate_on_submit():
        with db_session:
            url.cat = OldCategory[form.cat.data]
            url.lang = form.lang.data
            url.is_main = form.is_main.data
            url.deleted = form.deleted.data
            commit()
        flash('Изменения сохранены %s' % form.cat.data, 'success')
        if current_cat != url.cat:
            move_url_screens(url.id, current_cat.id, url.cat.id)
            flash('Скрины перемещены', 'success')
        next = Url.select(lambda u: u.id > url.id and u.cat == current_cat).order_by(Url.id).first()
        if next:
            return redirect('/url/%s' % next.id)
        return redirect('/url/%s' % url.id)
    else:
        next = Url.select(lambda u: u.id > url.id and u.cat == current_cat).order_by(Url.id).first()
        prev = Url.select(lambda u: u.id < url.id and u.cat == current_cat).order_by(desc(Url.id)).first()
        return render_template('url.html', url=url, next=next, prev=prev, form=form)


@csp_header({"default-src": "'self'", "script-src": "'self'", "worker-src": "'self'"})
@common.route('/markup/<int:url_id>', methods=['GET', 'POST'])
def markup(url_id: int):
    url = Url[url_id]
    current_cat = url.cat
    if request.method == 'POST':
        train_markup = request.form.get('markup')
        return jsonify({'success': True, 'data': train_markup})
    markup = json.dumps(url.markup.markup)
    next = Url.select(lambda u: u.id > url.id and u.cat == current_cat).order_by(Url.id).first()
    prev = Url.select(lambda u: u.id < url.id and u.cat == current_cat).order_by(desc(Url.id)).first()
    return render_template('markup.html', url=url, markup=markup, next=next, prev=prev)


@db_session
@common.route('/url/toggle/<int:url_id>/attr/<attr>', methods=['POST', 'AJAX'])
def toggle_attr(url_id: int, attr: str):
    url = Url[url_id]
    if not url or attr not in ['lang', 'is_main', 'deleted', 'bad_image']:
        abort(404)
    if attr == 'lang':
        url.lang = 'ru'
    else:
        val = getattr(url, attr)
        setattr(url, attr, not val)
    commit()
    return jsonify({'success': True, 'attr': attr, 'new val': getattr(url, attr)})


@db_session
@common.route('/url/layout/<int:url_id>', methods=['POST'])
def update_layout(url_id: int):
    url = Url[url_id]
    if not url:
        abort(404)
    form = LayoutForm(obj=url)
    if form.validate_on_submit():
        url.layout = form.layout.data
        commit()
    return jsonify({'success': True, 'layout': url.layout})


@db_session
@common.route('/url/text-refresh/<int:url_id>', methods=['GET'])
def update_text(url_id: int):
    try:
        url = Url[url_id]
        if not url:
            abort(404)
        title, meta, text = extract_text_title_meta(url.html.html_js)
        url.text.title = title
        url.text.raw_text = text
        url.text.meta_keys = meta['keys']
        url.text.meta_desc = meta['desc']
        commit()
        flash('text has been updated', 'success')
    except Exception:
        flash('fail text refresh', 'error')
    return redirect('/url/%s' % url_id)


@db_session
@common.route('/url/screen-refresh/<int:url_id>', methods=['GET', 'POST'])
def update_screen(url_id: int):
    url = Url[url_id]
    if not url:
        abort(404)
    rq_job = current_app.task_queue.enqueue('app.tasks.update_screen', url_id)
    task = Task(
        id=rq_job.get_id(),
        name='update_screen',
        payload={'url_id': url_id}
    )
    commit()
    if request.method == 'GET':
        flash(f'task {task.id} was queued', 'success')
        return redirect('/url/%s' % url_id)
    else:

app/templates/cat.html
{% extends "layout.html" %}
{% import 'macros.html' as macros %}

{% set title = cat.name %}
{% block heading %}  <h1>[{{ cat.id }}] {{ cat.name }}</h1> {% endblock %}
{% block content %}
    {{ macros.search_form(url_for(route, page=1, sort='', dir='asc', idx=cat.id)) }}
    {{ macros.pagination(route, page, max_page, sort, dir, cat.id, search) }}
    <table class="table table-condensed table-hover">
        <thead>
        <tr>
            <th>id</th>
            <th>url</th>
            <th>title</th>
            <th>text</th>
            <th>approve</th>
        </tr>
        </thead>
        <tbody>
        {% for url in urls %}
            <tr>
                <td><a id="#{{ url.id }}" href="{{ url_for('common.show', url_id=url.id) }}">{{ url.id }}</a></td>
                <td>
                    <a href="{{ url.url }}" target="_blank">{{ url.url }}</a><br/>
                    <b>{{ url.lang| upper }}</b> Is Main:
                    {{ macros.bool_toogle(url.is_main, url_for('common.toggle_attr', url_id=url.id, attr='is_main'), url.id, '') }}<br/>
                    Has html:  {{ macros.bool_mark(url.has_html) }} Has markup:  {{ macros.bool_mark(url.has_markup) }}
                </td>
                <td>{{ url.text.title }}</td>
                <td>
                    {{ url.text.raw_text[:250] }}
                    <a data-toggle="collapse" href="#collapse_{{ url.id }}" role="button">Show/Hide</a>
                    <div class="collapse" id="collapse_{{ url.id }}">
                        {{ url.text.raw_text }}
                    </div>
                </td>
                <td>
                    <a href="{{ url_for('common.show', url_id=url.id) }}" target="_blank"
                       class="btn btn-sm btn-primary">
                        <i class="fas fa-eye"></i>
                    </a><br/>

                    <br>
                    {{
                        macros.bool_toogle(
                            (url.lang=='ru'), url_for('common.toggle_attr', url_id=url.id, attr='lang'),
                            url.id, 'RU'
                         )
                     }}
                    <br>
                    {{
                        macros.bool_toogle(
                            url.deleted, url_for('common.toggle_attr', url_id=url.id, attr='deleted'),
                            url.id, 'Delete'
                         )
                     }}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

       {{ macros.pagination(route, page, max_page, sort, dir, cat.id, search) }}
{% endblock %}

app/templates/images.html
{% extends "layout.html" %}
{% import 'macros.html' as macros %}

{% set title = 'Page#' ~ page %}
{% block heading %}   {% endblock %}
{% block content %}
    {{ macros.search_form(url_for('common.image_index', page=1, sort='', dir='asc')) }}
    {{ macros.pagination(route, page, max_page, sort, dir, None, search) }}
    <div class="card-columns">
    {% for url in urls -%}
        <div class="card">
            <a href="{{ url.get_thumb_url() }}" target="_blank">
                <img class="card-img-top zoomable" src="{{ url.get_thumb_url() }}">
            </a>
            <div class="card-body">
                <h5 class="card-title">
                    #{{ loop.index }}
                    <a href="{{ url.url }}" target="_blank">{{ url.url }}</a>
                </h5>
                <p class="card-text">
                    (1024 x {{ url.markup.height }})
                    Elements: {{ url.markup.elem_count }}
                    Depth: {{ url.markup.max_depth }}
                    <a class="expand_img btn btn-sm btn-outline-info" href="#" data-src="{{ url.get_image_url() }}"
                       target="_blank">
                        Full image
                    </a>
                    <a href="{{ url_for('common.show', url_id=url.id) }}" target="_blank" title="Show"
                       class="btn btn-sm btn-primary">
                        <i class="fas fa-eye"></i>
                    </a>
                    <a href="{{ url_for('common.markup', url_id=url.id) }}" target="_blank" title="Markup"
                       class="btn btn-sm btn-primary">
                        <i class="fas fa-edit"></i>
                    </a>
                    <a href="{{ url_for('common.update_data', url_id=url.id) }}" target="_blank" title="Refresh data"
                       class="btn btn-sm btn-warning">
                        <i class="fas fa-file-code"></i>
                    </a>

                     <a href="{{ url_for('common.update_screen', url_id=url.id) }}" target="_blank" title="Refresh image"
                       class="btn btn-sm btn-info">
                        <i class="fas fa-file-image"></i>
                    </a>
                    {{ macros.bool_toogle(
                            url.bad_image, url_for('common.toggle_attr', url_id=url.id, attr='bad_image'),
                            url.id, 'Bad image mark'
                         ) }}
                    <br/>
                <form action="{{ url_for('common.update_layout', url_id=url.id) }}" class="form">
                    {{ forms[url.id].csrf_token }}
                    <div class="form-group required">
                        <label for="{{ forms[url.id].layout.id }}"
                               class="form-control-label">{{ forms[url.id].layout.label }}</label>
                        {{ forms[url.id].layout(class_="form-control") }}
                    </div>
                    <button class="btn btn-ajax btn-sm btn-secondary">Upd</button>
                </form>
                </p>
            </div>
        </div>
    {% endfor -%}
    </div>
    {{ macros.pagination(route, page, max_page, sort, dir, None, search) }}

    {{ macros.image_modal() }}
{% endblock %}

app/templates/index.html
{% extends "layout.html" %}

{% block title %}
    Categories
{% endblock %}
{% block heading %}  <h1>Categories</h1> {% endblock %}

{% block content %}
    <table class="table table-condensed">
        <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>total urls</th>
            <th>with markup</th>
            <th>--</th>
        </tr>
        </thead>
        <tbody>
        {% for cat in categories %}
            {% set c = cat[0] %}
            <tr>
                <td>{{ c.id }}</td>
                <td><a href="{{ url_for('common.cat', idx=c.id) }}">{{ c.name }}</a></td>
                <td>{{ cat[1] }}</td>
                <td>{{ with_markup[c.id] or '0' }}</td>
                <td>
                    <a href="{{ url_for('common.cat', idx=c.id) }}">all</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/layout.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% if title %}
    <title>{{title}} - html markup app</title>
    {% else %}
    <title>Html Markup</title>
    {% endif %}
    <link rel="stylesheet" href="/static/app.css">
   {{ fontawesome_html() }}
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
<a class="navbar-brand" href="#">Demo app</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarCollapse">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('common.old_index') }}">Old cats</a>
    </li>
       <li class="nav-item">
      <a class="nav-link" href="{{ url_for('common.image_index') }}">Images</a>
    </li>
  </ul>
    <ul class="navbar-nav mr-auto nav-justified">
        <li class="nav-item">
        {% block heading %}{% endblock %}
        </li>
    </ul>
</div>
</nav>

<main role="main" class="container">
<div class="inner-container">
{% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
{% endwith %}
{% block content %}
{% endblock %}
</div>
</main>
<script src="/static/app.js"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

app/templates/macros.html
{% macro form_group(field) -%}
    <div class="form-group required">
        <label for="{{ field.id }}" class="form-control-label">{{ field.label }}</label>
        {% if field.errors %}
            {{ field(class_="form-control is-invalid") }}
        {% else %}
            {{ field(class_="form-control") }}
        {% endif %}
        {% if field.errors %}
            <div class="invalid-feedback">
                {{ field.errors[0] }}
            </div>
        {% endif %}
    </div>
{% endmacro %}

{% macro checkbox(field) -%}
    <div class="form-check">
        {% if field.errors %}
            {{ field(class_="form-check-input is-invalid") }}
        {% else %}
            {{ field(class_="form-check-input") }}
        {% endif %}
        <label class="form-check-label" for="{{ field.id }}">
            {{ field.label }}
        </label>
        {% if field.errors %}
            <div class="invalid-feedback">
                {{ field.errors[0] }}
            </div>
        {% endif %}
    </div>

{% endmacro %}

{% macro quick_form(form, action='') -%}
    {% if action %}
        <form class="form" method="POST" action="{{ action }}">
    {% else %}
        <form class="form" method="POST">
    {% endif %}
    <form class="form" method="POST">
        {% for field in form %}
            {% if field.type in ('HiddenField', 'CSRFTokenField') %}
                {{ field() }}
            {% elif field.type == 'SubmitField' %}
                {{ field(class_="btn btn-primary") }}
            {% elif field.type == 'BooleanField' %}
                {{ checkbox(field) }}
            {% else %}
                {{ form_group(field) }}
            {% endif %}
        {% endfor %}
    </form>
{% endmacro %}

{% macro bool_mark(val) -%}
    {% if val %}
        <span class="text-success"><i class="fas fa-check-circle"></i></span>
    {% else %}
        <span class="text-danger"><i class="fas fa-circle"></i></span>
    {% endif %}
{% endmacro -%}

{% macro bool_toogle(val, url, id, label) -%}
    {% if val %}
        <a class="text-success atoggle" data-url="{{ url }}" data-val="true" href="#{{ id }}">
            <i class="fas fa-check-circle"></i> {{ label }}
        </a>
    {% else %}
        <a class="text-danger atoggle" data-url="{{ url }}" data-val="false" href="#{{ id }}">
            <i class="fas fa-circle"></i> {{ label }}
        </a>
    {% endif %}
{% endmacro -%}

{% macro pagination(route, curr_page, max_page, sort, dir, idx=None, search='') -%}
    <nav>
        <ul class="pagination">
            {% if curr_page > 1 %}
                <li class="page-item">
                    <a class="page-link"
                       href="{{ url_for(route, idx=idx, sort=sort, dir=dir, page=1, search=search) }}">
                        First
                    </a>
                </li>

            {% endif %}
            {% set min_nav = (1, curr_page - 5)|max %}
            {% set max_nav = (max_page, curr_page + 5)|min %}
            {% for i in range(min_nav, max_nav) %}
                <li class="page-item">
                    {% if i == curr_page|int %}
                        <li class="page-item active">
                            <a class="page-link" href="#">{{ i }}</a>
                            {% else %}
                        <li class="page-item">
                        {% if idx %}
                            <a class="page-link"
                               href="{{ url_for(route, idx=idx, sort=sort, dir=dir, page=i, search=search) }}">
                                {{ i }}
                            </a>
                        {% else %}
                            <a class="page-link"
                               href="{{ url_for(route, sort=sort, dir=dir, page=i, search=search) }}">
                                {{ i }}
                            </a>
                        {% endif %}
                    {% endif %}
                    </li>
            {% endfor %}

            {% if curr_page != max_page %}
                <li class="page-item">
                    {% if idx %}
                        <a class="page-link"
                           href="{{ url_for(route, idx=idx, sort=sort, dir=dir, page=max_page, search=search) }}">
                            Last
                        </a>
                    {% else %}
                        <a class="page-link"
                           href="{{ url_for(route, sort=sort, dir=dir, page=max_page, search=search) }}">
                            Last
                        </a>
                    {% endif %}
                </li>
            {% endif %}
        </ul>
    </nav>
{% endmacro -%}

{% macro image_modal() -%}
    <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Image preview</h4>
                </div>
                <div class="modal-body">
                    <img src="" id="imagepreview" style="width: 80%;">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endmacro -%}

{% macro search_form(action_link) -%}
    <form class="form-inline md-form form-sm active-purple-2 mt-2" action="{{ action_link }}" method="get">
        <div class="input-group mb-3">
            <input class="form-control form-control-sm " type="text" placeholder="Search"
                   aria-label="Search" name="search">
            <div class="input-group-append">
                <button class="btn btn-outline-info btn-sm" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>
{% endmacro -%}

app/templates/markup.html
{% extends "layout.html" %}
{% import 'macros.html' as macros %}

{% set title = url.cat.name ~' : ' ~ url.url %}
{% block heading %}    <h1 class="h1"> {{ url.cat.name }}: {{ url.url }} </h1> {% endblock %}

{% block content %}
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('common.show', url_id=url.id) }}">Edit</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('common.markup', url_id=url.id) }}">Markup</a>
        </li>
    </ul>
    <nav>
        <ul class="pagination">
            {% if prev %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('common.markup', url_id=prev.id) }}">Previous</a>
                </li>
            {% endif %}
            {% if next %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('common.markup', url_id=next.id) }}">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>

    <div class="card card-header">
        <div class="card-header">
            ID: {{ url.id }} URL: <a href="{{ url.url }}" target="_blank">{{ url.url }}</a><br/>
            MarkupElements: {{ url.markup.elem_count }}
        </div>
    </div>

    <div id="markuper">
        <markup
                image="{{ url.get_image_url() }}"
                save-url="{{ url_for('common.markup', url_id=url.id) }}"
                :markup="{{ markup }}"
                :marked="[]"
        />
    </div>
{% endblock %}

app/templates/old_index.html
{% extends "layout.html" %}

{% block title %}
    Old Categories
{% endblock %}
{% block heading %}  <h1> Old Categories</h1> {% endblock %}

{% block content %}
    <table class="table table-condensed">
        <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>total urls</th>
        </tr>
        </thead>
        <tbody>
        {% for cat in categories %}
            {% set c = cat[0] %}
            <tr>
                <td>{{ c.id }}</td>
                <td><a href="{{ url_for('common.old_cat', idx=c.id) }}">{{ c.name }}</a></td>
                <td>{{ cat[1] }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/templates/url.html
{% extends "layout.html" %}
{% import 'macros.html' as macros %}

{% set title = url.cat.name ~' : ' ~ url.url %}

{% block heading %}    <h1 class="h1"> {{ url.cat.name }}: {{ url.url }} </h1> {% endblock %}

{% block content %}
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('common.show', url_id=url.id) }}">Edit</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{{ url_for('common.markup', url_id=url.id) }}">Markup</a>
        </li>
    </ul>

    <nav>
        <ul class="pagination">
            {% if prev %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('common.show', url_id=prev.id) }}">Previous</a>
                </li>
            {% endif %}
            {% if next %}
                <li class="page-item">
                    <a class="page-link" href="{{ url_for('common.show', url_id=next.id) }}">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>

    <div class="card">
        <div class="card-header">
            ID: {{ url.id }} URL: <a href="{{ url.url }}" target="_blank">{{ url.url }}</a>
            <a href="{{ url_for('common.update_text', url_id=url.id) }}" class="btn btn-sm btn-primary float-right">
                Refresh text
            </a>
            <a href="{{ url_for('common.update_screen', url_id=url.id) }}" target="_blank" title="Refresh image"
               class="btn btn-sm btn-info float-right">
                <i class="fas fa-file-image"></i>
            </a>
            <a href="{{ url_for('common.update_data', url_id=url.id) }}" target="_blank" title="Refresh data"
               class="btn btn-sm btn-warning float-right">
                <i class="fas fa-file-code"></i>
            </a>
        </div>
        <div class="card-body">
            <h5 class="card-title">
                {{ url.text.title }}
            </h5>
            <p class="card-text">
            <div class="row">
                <div class="col-md-6">
                    <a href="{{ url.get_thumb_url() }}" target="_blank">
                        <img class="card-img zoomable" src="{{ url.get_thumb_url() }}">
                    </a>
                    <a class="expand_img mt-5 btn btn-sm btn-outline-info" href="#" data-src="{{ url.get_image_url() }}"
                       target="_blank">
                        Full image (1024 x {{ url.markup.height }})
                    </a>
                    <div class="block mt-5 scrollable h200">
                        {{ url.text.raw_text }}
                    </div>
                </div>
                <div class="col-md-6">
                    <dl>
                        <dd>Elements:</dd> <dt>{{ url.markup.elem_count }}</dt>
                        <dd>Depth:</dd> <dt>{{ url.markup.max_depth }}</dt>
                        <dd>Lemmas:</dd> <dt>{{ url.text.lemmas_count }}</dt>
                    <div class="block mt-5 scrollable h200">
                        {{ url.text.lemmas }}
                    </div>
                    {{ macros.quick_form(form) }}
                </div>
            </div>
            <ul class="pagination mt-5">
                {% if prev %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('common.show', url_id=prev.id) }}">Previous</a>
                    </li>
                {% endif %}
                {% if next %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('common.show', url_id=next.id) }}">Next</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    {{ macros.image_modal() }}
{% endblock %}